### ISSUE TITLE
Damaged dmg Issue

### ISSUE THREAD

**Issue by os2992** [nigification/Flowgorithm-Mac-OSX#19]
Hi, 

Program couldnt be opened. Macos (ventura) warned about application is damaged cant be opened you shoul move it to the trash.

I hope it can be solved.

Regards

**Comment by jostasik** [comment]
Hello! 
After you drag Flowgorithm to your applications folder, open terminal and then paste this command:
```shell
xattr -d com.apple.quarantine /Applications/Flowgorithm.app
```
Flowgorithm should then be able to open up normally. Let me know if you have any other issues!

**Comment by jostasik** [comment]
@os2992 Let me know if you have any other issues!

**Comment by cryptobyls** [comment]
Hello, The fix worked fine for me with the V.4 beta. Thanks
