### ISSUE TITLE
How to transfer files to finder?

### ISSUE THREAD

**Issue by Kaiji-Key** [nigification/Flowgorithm-Mac-OSX#22]
Whenever I go to save a project, it saves itself to a virtual pc it seems. I'm wondering if there's a way to transfer these files to my actual computer?

**Comment by jostasik** [comment]
![image](https://github.com/jostasik/Flowgorithm-macOS/assets/31175268/a592d9cd-9eee-40e2-8ca5-47d4f89a7de4)
In this window that pops up, your real Mac hard drive will show up as the Z drive! The one I have selected here for example. :)

**Comment by Kaiji-Key** [comment]
Hmm... Now I'm getting this error
<img width="510" alt="Screenshot 2023-08-20 at 9 54 02 PM" src="https://github.com/jostasik/Flowgorithm-macOS/assets/123205194/f1e54ae3-84cd-4a8b-8011-f46d2d3803e1">

**Comment by Kaiji-Key** [comment]
do you know what this error means?

**Comment by Kaiji-Key** [comment]
never mind; i figured it out!

**Comment by lancevV** [comment]
> Hmm... Now I'm getting this error <img alt="Screenshot 2023-08-20 at 9 54 02 PM" width="510" src="https://user-images.githubusercontent.com/123205194/261892827-f1e54ae3-84cd-4a8b-8011-f46d2d3803e1.png">

how did you fix this? im having the same issue

**Comment by Kaiji-Key** [comment]
> > Hmm... Now I'm getting this error <img alt="Screenshot 2023-08-20 at 9 54 02 PM" width="510" src="https://user-images.githubusercontent.com/123205194/261892827-f1e54ae3-84cd-4a8b-8011-f46d2d3803e1.png">
> 
> how did you fix this? im having the same issue

once you go into the z file, go to users, click on your user, then go to downloads.

from my understanding, trying to save to the main z file is trying to save to the main files of the computer that have your os, accounts, etc

**Comment by jostasik** [comment]
@Kaiji-Key Thanks for the explanation!
