### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by CrazyCratom** [nigification/Flowgorithm-Mac-OSX#25]
Hi, I ve got a problem. I completed installation successfully, but if I want to open it nothing happened. But I really don't know why?

**Comment by jostasik** [comment]
Hey sorry you're having an issue. What version of macos are you on? Have you already tried the troubleshooting steps?

Did you install using [Homebrew](https://github.com/jostasik/Flowgorithm-macOS#option-1-use-homebrew) or did you [download from github](https://github.com/jostasik/Flowgorithm-macOS#option-2-download-the-latest-release)?

**Comment by CrazyCratom** [comment]
I have MacOS version 13.4 if iam seeing good. I have a mac only about a day so :D.
I downloaded Homebrew and then Flowgorithm installer. I tried your problem steps but nothing helped.
I can see a Flowgorithm "icon" but when I try to turn it on nothing happening.

**Comment by ne0c0de** [comment]
I'm using MBP 2019 and Ventura 13.5.2 and when I tried to open the app, it's saying this:
<img width="372" alt="image" src="https://github.com/jostasik/Flowgorithm-macOS/assets/1671892/5d79d0fe-d077-4823-9499-cbd95726e03f">

**Comment by jostasik** [comment]
> I'm using MBP 2019 and Ventura 13.5.2 and when I tried to open the app, it's saying this: <img alt="image" width="372" src="https://user-images.githubusercontent.com/1671892/274934459-5d79d0fe-d077-4823-9499-cbd95726e03f.png">

@ne0c0de This issue can be solved by re-installing flowgorithm; but then before trying to open it, run the following command: `xattr -d com.apple.quarantine /Applications/Flowgorithm.app`

Though installing via [Method 1](https://github.com/jostasik/Flowgorithm-macOS#option-1-use-homebrew) bypasses this issue.

**Comment by ne0c0de** [comment]
it works, thank you so much.

**Comment by jostasik** [comment]
awesome i'm glad!!

**Comment by CrazyCratom** [comment]
I tried everythink but my problem still persists :(

**Comment by merenyimiklos** [comment]
> I tried everythink but my problem still persists :(

you should reinstall and download again the application and after before you start the app in the terminal copy this code:
`xattr -d com.apple.quarantine /Applications/Flowgorithm.app`

and it will be good!
